title:               'Jeff Brozena'
include:             ['_pages']
exclude:             ['_includes/notes_graph.json', '_notes/templates/litnote.md']
# You may need to change the base URL depending on your deploy configuration.
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: false

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-wikirefs
  - jekyll-paginate
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /notes/:slug
  nobody-falls-halfway:
    output: true
    permalink: /nobody-falls-halfway/:path/

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

wikilinks:
  attributes:
    enabled: true
  case:
    'lower case'
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'notes'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []
